### ISSUE TITLE
Elm 0.19 running in debug

### ISSUE THREAD

**Issue by DiegoGallegos4** [ContaSystemer/elm-menu#2]
**Describe the bug**
when trying to build a file with --debug flag, build failes.

**To Reproduce**
Build file with this lib.

**Expected behavior**
Should build correctly in debug mode

**Additional context**
```
# CallStack (from HasCallStack):
#   error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal
```

**Comment by akoppela** [comment]
@DiegoGallegos4 Hello, this is [the known issue] of the Elm compiler. Should be fixed in the next release. 

[the known issue]: https://github.com/elm/compiler/issues/1851
