### ISSUE TITLE
Elm css version

### ISSUE THREAD

**Issue by tesk9** [ContaSystemer/elm-menu#7]
**Is your feature request related to a problem? Please describe.**

rtfeldman released a new version of `elm-css` ([17.0.1](https://github.com/rtfeldman/elm-css/releases/tag/17.0.1)) that works with the [Dark Reader extension](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US). See https://github.com/rtfeldman/elm-css/pull/542.

The bounds of `elm-menu`'s use of `elm-css` are `"rtfeldman/elm-css": "16.1.1 <= v < 17.0.0"`

**Describe the solution you'd like**

I'd love a new version of `elm-menu` to be released with bounds including `17.0.1`.

**Additional context**

Thank you for considering!

**Comment by akoppela** [comment]
Sure. I’ll release new version either on the weekend on start of next week.
