### ISSUE TITLE
elm-css 18.0.0

### ISSUE THREAD

**Issue by tesk9** [ContaSystemer/elm-menu#9]
**Is your feature request related to a problem? Please describe.**
Currently, this package requires use with `"rtfeldman/elm-css": "17.0.1 <= v < 18.0.0"`. [elm-css 18.0.0](https://package.elm-lang.org/packages/rtfeldman/elm-css/18.0.0/) has been published.

**Describe the solution you'd like**
Ideally, I'd love extended elm-css version support: `"rtfeldman/elm-css": "17.0.1 <= v < 19.0.0"`.

**Additional context**
Thank you!

**Comment by akoppela** [comment]
Sure thing.

**Comment by akoppela** [comment]
Published 1.1.2.

**Comment by tesk9** [comment]
Thank you!
